import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/accountcreation">AccountCreation</Link>
        </li>
        <li>
          <Link to="/feedbackcollection">FeedbackCollection</Link>
        </li>
        <li>
          <Link to="/invoicebilling">InvoiceBilling</Link>
        </li>
        <li>
          <Link to="/multiplecurrencysupport">Multiplecurrencysupport</Link>
        </li>
        <li>
          <Link to="/notifications">Notifications</Link>
        </li>
        <li>
          <Link to="/review">Review</Link>
        </li>
        <li>
          <Link to="/payments">Payments</Link>
        </li>
        <li>
          <Link to="/premiumplancomparison">PremiumPlanComparison</Link>
        </li>
        <li>
          <Link to="/guestlogin">GuestLogin</Link>
        </li>
        <li>
          <Link to="/refundmanagement">RefundManagement</Link>
        </li>
        <li>
          <Link to="/customadvertisement">CustomAdvertisement</Link>
        </li>
        <li>
          <Link to="/reorderpurchase">ReorderPurchase</Link>
        </li>
        <li>
          <Link to="/savedcards">SavedCards</Link>
        </li>
        <li>
          <Link to="/emailsignin">EmailSignin</Link>
        </li>
        <li>
          <Link to="/taxcalculator">TaxCalculator</Link>
        </li>
        <li>
          <Link to="/employeelogin">Employeelogin</Link>
        </li>
        <li>
          <Link to="/facebooksigninone">FacebookSigninOne</Link>
        </li>
        <li>
          <Link to="/landingpage">LandingPage</Link>
        </li>
        <li>
          <Link to="/phonelogin">PhoneLogin</Link>
        </li>
        <li>
          <Link to="/paytmintegration">PaytmIntegration</Link>
        </li>
        <li>
          <Link to="/gallery">Gallery</Link>
        </li>
        <li>
          <Link to="/signin">Signin</Link>
        </li>
        <li>
          <Link to="/signuploginmodule">SignupLoginModule</Link>
        </li>
        <li>
          <Link to="/termsandconditions">TermsAndConditions</Link>
        </li>
        <li>
          <Link to="/tutorials">Tutorials</Link>
        </li>
        <li>
          <Link to="/twofactorauthentication">Twofactorauthentication</Link>
        </li>
        <li>
          <Link to="/stripeintegration">StripeIntegration</Link>
        </li>
        <li>
          <Link to="/twiliointegration">TwilioIntegration</Link>
        </li>
        <li>
          <Link to="/slideshowcreator">SlideshowCreator</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
